"""Reproduce all three release demos through the installed CLI. No model key required."""

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps

from eas_visual.pixels import pixel_hash

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "examples" / "visual" / "assets"
MOUTH = [
    [400, 518],
    [478, 500],
    [494, 517],
    [513, 552],
    [514, 574],
    [499, 588],
    [476, 596],
    [450, 590],
    [435, 578],
    [418, 552],
]


def floorplan(path):
    """Original demo artwork, generated by this repository (MIT)."""
    image = Image.new("RGB", (480, 320), "#f7f5ef")
    d = ImageDraw.Draw(image)
    d.rectangle((14, 14, 465, 305), fill="#ddd1ba", outline="#414e58", width=7)
    d.rectangle((48, 72, 127, 191), fill="#415b6d")
    d.rectangle((52, 76, 123, 187), fill="#78aabb")
    d.rectangle((56, 80, 119, 107), fill="#fff6df", outline="#415b6d", width=2)
    d.line((52, 117, 123, 117), fill="#415b6d", width=2)
    d.rectangle((48, 215, 127, 252), fill="#9f7051", outline="#415b6d", width=2)
    d.rectangle((350, 35, 438, 55), fill="#a9dcea", outline="#415e68", width=2)
    d.text((28, 30), "BEDROOM / LOCAL MOVE", fill="#34434a")
    d.text((230, 267), "floor and details stay intact", fill="#34434a")
    image.save(path)


def read_record(project):
    manifest = json.loads((project / "manifest.json").read_bytes())
    return json.loads((project / manifest["revisions"][manifest["current_revision"]]["path"]).read_bytes())


def preview(path, title, panels, note="", crop=None, columns=3, cell=(440, 300)):
    w, h = cell
    rows = (len(panels) + columns - 1) // columns
    canvas = Image.new("RGB", (columns * w, 94 + rows * (h + 38) + 48), "#111c25")
    draw = ImageDraw.Draw(canvas)
    font = ImageFont.load_default(size=22)
    small = ImageFont.load_default(size=15)
    draw.text((20, 16), title, font=font, fill="#f6f4ec")
    draw.text((20, 52), note, font=small, fill="#80d9c5")
    for i, (label, source) in enumerate(panels):
        image = (
            source.convert("RGB") if isinstance(source, Image.Image) else Image.open(source).convert("RGB")
        )
        if crop:
            image = image.crop(crop)
        fitted = ImageOps.contain(
            image, (w - 20, h - 12), Image.Resampling.NEAREST if crop else Image.Resampling.LANCZOS
        )
        x, y = (i % columns) * w, 94 + (i // columns) * (h + 38)
        draw.text((x + 12, y), label, font=small, fill="#ffffff")
        canvas.paste(fitted, (x + (w - fitted.width) // 2, y + 28 + (h - fitted.height) // 2))
    draw.text(
        (20, canvas.height - 28),
        "EAS Visual 0.1 Experimental | explicit masks | immutable baseline | verified history",
        font=small,
        fill="#a9bac8",
    )
    canvas.save(path)


def comparison(folder, project, before, result, title, crop):
    original = Image.open(before).convert("RGB")
    edited = Image.open(result["output_png"]).convert("RGB")
    record = read_record(project)
    mask = Image.open(project / record["editable_support"]["path"]).convert("L")
    support = np.asarray(mask) > 0
    delta = np.max(np.abs(np.asarray(original, dtype=np.int16) - np.asarray(edited, dtype=np.int16)), axis=2)
    heat = np.zeros((*delta.shape, 3), dtype=np.uint8)
    heat[delta > 0] = [255, 70, 90]
    untouched = heat.copy()
    untouched[support] = 0
    overlay = np.asarray(original).copy()
    overlay[support] = (overlay[support] * 0.4 + np.array([20, 210, 175]) * 0.6).astype(np.uint8)
    for filename, image in [
        ("original.png", original),
        ("edited.png", edited),
        ("editable-mask.png", mask),
        ("diff.png", Image.fromarray(heat)),
        ("untouched-diff.png", Image.fromarray(untouched)),
    ]:
        image.save(folder / filename)
    panels = [
        ("Original / previous revision", original),
        ("Editable support", Image.fromarray(overlay)),
        ("Edited / EAS SVG rendered", edited),
        ("Changed pixels", Image.fromarray(heat)),
        ("Untouched-region diff", Image.fromarray(untouched)),
        ("Mask (white = authorized)", mask),
    ]
    note = f"untouched changed pixels: {result['validation']['untouched_changed_pixels']} | support: {support.mean() * 100:.4f}%"
    preview(folder / "comparison.png", title, panels, note)
    preview(folder / "zoom.png", title + " / pixel detail", panels, note, crop=crop)
    (folder / "metrics.json").write_text(json.dumps(record["validation"], indent=2) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "build" / "visual-demo")
    parser.add_argument("--case", choices=["all", "structural", "generative", "undo"], default="all")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=False)
    journal, report = [], {}

    def cli(*arguments):
        start = time.perf_counter()
        command = [sys.executable, "-m", "eas_visual.cli", *map(str, arguments), "--json"]
        completed = subprocess.run(
            command, capture_output=True, text=True, encoding="utf-8", timeout=300, check=False
        )
        entry = {
            "arguments": list(map(str, arguments)),
            "seconds": time.perf_counter() - start,
            "exit_code": completed.returncode,
        }
        journal.append(entry)
        (args.output / "cli-journal.json").write_text(json.dumps(journal, indent=2) + "\n", encoding="utf-8")
        if completed.returncode:
            raise RuntimeError(f"CLI failed (no retry): {entry}\n{completed.stdout}\n{completed.stderr}")
        response = json.loads(completed.stdout)
        assert response["ok"]
        return response["result"]

    if args.case in ("all", "structural", "undo"):
        folder = args.output / "01-structural"
        folder.mkdir()
        source = folder / "input.png"
        floorplan(source)
        project = folder / "room.eas"
        baseline = cli("init", source, "-o", project)
        promoted = cli("promote", project, "--label", "bed", "--bbox", "[48,72,128,192]")
        moved = cli(
            "move", project, "--object", "bed", "--dx", "164", "--dy", "0", "--donor", "[350,160,390,200]"
        )
        cli("render", project, "-o", folder / "edited.svg")
        comparison(
            folder,
            project,
            baseline["output_png"],
            moved,
            "Demo 1 / Move the bed to the right",
            [38, 62, 302, 205],
        )
        assert moved["validation"]["untouched_changed_pixels"] == 0
        report["structural"] = {
            "validation": moved["validation"],
            "object_appearance_mae": read_record(project)["object_appearance_mae"],
            "repair_quality": "flat synthetic floor: exact; not a complex-inpainting claim",
        }
        if args.case in ("all", "undo"):
            undo_folder = args.output / "03-undo"
            undo_folder.mkdir()
            # move is edit 1; a second move is edit 2. Promotion precedes this sequence.
            second = cli(
                "move", project, "--object", "bed", "--dx", "50", "--dy", "0", "--donor", "[350,160,390,200]"
            )
            undo1 = cli("undo", project)
            undo2 = cli("undo", project)
            redo = cli("redo", project)
            assert undo1["output_hash"] == moved["output_hash"]
            assert undo2["output_hash"] == promoted["output_hash"]
            assert redo["output_hash"] == moved["output_hash"]
            replay = cli("replay", project)
            stages = [
                ("edit 1", moved),
                ("edit 2", second),
                ("undo -> edit 1", undo1),
                ("undo -> baseline pixels", undo2),
                ("redo -> edit 1", redo),
            ]
            preview(
                undo_folder / "comparison.png",
                "Demo 3 / AI editing is reversible",
                [(name, state["output_png"]) for name, state in stages],
                "edit / edit / undo / undo / redo: all expected hashes match",
            )
            report["undo"] = {
                "stages": [
                    {"operation": name, "revision": state["revision"], "hash": state["output_hash"]}
                    for name, state in stages
                ],
                "all_expected_hashes_match": True,
                "replay": replay,
            }
            (undo_folder / "hashes.json").write_text(
                json.dumps(report["undo"], indent=2) + "\n", encoding="utf-8"
            )
    if args.case in ("all", "generative"):
        folder = args.output / "02-generative"
        folder.mkdir()
        project = folder / "character.eas"
        baseline = cli("init", ASSETS / "wikipe-tan-input.png", "-o", project)
        cli("promote", project, "--label", "mouth", "--polygon", json.dumps(MOUTH))
        request = cli(
            "prepare",
            project,
            "--object",
            "mouth",
            "--instruction",
            "Make her smile gently.",
            "--context",
            "[280,290,760,670]",
            "--margin",
            "3",
        )
        # A real, previously generated crop is reused. Verify its original input pixels exactly.
        historical_context = Image.open(ASSETS / "mouth-provider-input.png").convert("RGB")
        assert pixel_hash(Image.open(request["context_file"])) == pixel_hash(historical_context)
        edited = cli(
            "edit",
            project,
            "--object",
            "mouth",
            "--provider",
            "external-patch",
            "--request",
            request["request_id"],
            "--patch",
            ASSETS / "mouth-provider-output.png",
            "--metadata",
            ASSETS / "mouth-provider-metadata.json",
            "--normalize",
        )
        cli("render", project, "-o", folder / "edited.svg")
        comparison(
            folder,
            project,
            baseline["output_png"],
            edited,
            "Demo 2 / Gentle smile, strictly local",
            [380, 470, 550, 620],
        )
        record = read_record(project)
        raw = Image.open(ASSETS / "mouth-provider-output.png")
        normalized = Image.open(project / record["provider"]["normalized_output"]["path"])
        before_crop = Image.open(request["context_file"]).convert("RGB")
        final_crop = Image.open(edited["output_png"]).crop(request["context_bbox"])
        accepted = final_crop.convert("RGBA")
        support_crop = Image.open(project / record["editable_support"]["path"]).crop(request["context_bbox"])
        accepted.putalpha(support_crop)
        accepted.save(folder / "accepted-patch.png")
        back = Image.new("RGBA", accepted.size, "#d6e3e8")
        back.alpha_composite(accepted)
        preview(
            folder / "provider-comparison.png",
            "A model may change context. EAS accepts only the declared support.",
            [
                ("Input context only", before_crop),
                ("Raw model output (wrong size)", raw),
                ("Explicitly normalized patch", normalized),
                ("Accepted patch / support", back),
                ("Final context", final_crop),
                ("Final diff", Image.open(folder / "diff.png").crop(request["context_bbox"])),
            ],
            "Cached real model output from prior POC; this demo makes zero new model calls",
        )
        assert edited["validation"]["untouched_changed_pixels"] == 0
        report["generative"] = {
            "validation": edited["validation"],
            "provider": record["provider"],
            "new_model_calls": 0,
            "kind": "real previous model crop, saved-output replay",
            "quality": "gentle smile visible; slight skin/seam differences remain; manual mask",
        }
    report["cli_calls"] = len(journal)
    report["cli_seconds"] = sum(entry["seconds"] for entry in journal)
    report["core_modified"] = False
    (args.output / "demo-report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "ok": True,
                "output": str(args.output),
                "cli_calls": len(journal),
                "seconds": report["cli_seconds"],
            }
        )
    )


if __name__ == "__main__":
    main()
